#ifdef	HAVE_CONFIG_H
# include "../config.h"
#endif
#include <unistd.h>
#include <errno.h>
#include "dict.h"

#if	ENABLE_NLS
# define	_(x)		gettext( x )
# define	N_(x)		x
#else
# define	_(x)		x
# define	N_(x)		x
#endif

static dict_entry_t const 	names[] =	{
	[ E2BIG ]	= { "E2BIG",	N_("Argument list too long") },
	[ EACCES ]	= { "EACCES",	N_("Permission denied") },
	[ EADDRINUSE ]	= { "EADDRINUSE",	N_("Address already in use") },
	[ EADDRNOTAVAIL ]	= { "EADDRNOTAVAIL",	N_("Cannot assign requested address") },
	[ EADV ]	= { "EADV",	N_("Advertise error") },
	[ EAFNOSUPPORT ]	= { "EAFNOSUPPORT",	N_("Address family not supported by protocol") },
	[ EAGAIN ]	= { "EAGAIN",	N_("Try again") },
	[ EALREADY ]	= { "EALREADY",	N_("Operation already in progress") },
	[ EBADE ]	= { "EBADE",	N_("Invalid exchange") },
	[ EBADF ]	= { "EBADF",	N_("Bad file number") },
	[ EBADFD ]	= { "EBADFD",	N_("File descriptor in bad state") },
	[ EBADMSG ]	= { "EBADMSG",	N_("Not a data message") },
	[ EBADR ]	= { "EBADR",	N_("Invalid request descriptor") },
	[ EBADRQC ]	= { "EBADRQC",	N_("Invalid request code") },
	[ EBADSLT ]	= { "EBADSLT",	N_("Invalid slot") },
	[ EBFONT ]	= { "EBFONT",	N_("Bad font file format") },
	[ EBUSY ]	= { "EBUSY",	N_("Device or resource busy") },
	[ ECANCELED ]	= { "ECANCELED",	N_("Operation Canceled") },
	[ ECHILD ]	= { "ECHILD",	N_("No child processes") },
	[ ECHRNG ]	= { "ECHRNG",	N_("Channel number out of range") },
	[ ECOMM ]	= { "ECOMM",	N_("Communication error on send") },
	[ ECONNABORTED ]	= { "ECONNABORTED",	N_("Software caused connection abort") },
	[ ECONNREFUSED ]	= { "ECONNREFUSED",	N_("Connection refused") },
	[ ECONNRESET ]	= { "ECONNRESET",	N_("Connection reset by peer") },
	[ EDEADLK ]	= { "EDEADLK",	N_("Resource deadlock would occur") },
	[ EDEADLOCK ]	= { "EDEADLOCK",	N_("") },
	[ EDESTADDRREQ ]	= { "EDESTADDRREQ",	N_("Destination address required") },
	[ EDOM ]	= { "EDOM",	N_("Math argument out of domain of func") },
	[ EDOTDOT ]	= { "EDOTDOT",	N_("RFS specific error") },
	[ EDQUOT ]	= { "EDQUOT",	N_("Quota exceeded") },
	[ EEXIST ]	= { "EEXIST",	N_("File exists") },
	[ EFAULT ]	= { "EFAULT",	N_("Bad address") },
	[ EFBIG ]	= { "EFBIG",	N_("File too large") },
	[ EHOSTDOWN ]	= { "EHOSTDOWN",	N_("Host is down") },
	[ EHOSTUNREACH ]	= { "EHOSTUNREACH",	N_("No route to host") },
	[ EHWPOISON ]	= { "EHWPOISON",	N_("Memory page has hardware error") },
	[ EIDRM ]	= { "EIDRM",	N_("Identifier removed") },
	[ EILSEQ ]	= { "EILSEQ",	N_("Illegal byte sequence") },
	[ EINPROGRESS ]	= { "EINPROGRESS",	N_("Operation now in progress") },
	[ EINTR ]	= { "EINTR",	N_("Interrupted system call") },
	[ EINVAL ]	= { "EINVAL",	N_("Invalid argument") },
	[ EIO ]	= { "EIO",	N_("I/O error") },
	[ EISCONN ]	= { "EISCONN",	N_("Transport endpoint is already connected") },
	[ EISDIR ]	= { "EISDIR",	N_("Is a directory") },
	[ EISNAM ]	= { "EISNAM",	N_("Is a named type file") },
	[ EKEYEXPIRED ]	= { "EKEYEXPIRED",	N_("Key has expired") },
	[ EKEYREJECTED ]	= { "EKEYREJECTED",	N_("Key was rejected by service") },
	[ EKEYREVOKED ]	= { "EKEYREVOKED",	N_("Key has been revoked") },
	[ EL2HLT ]	= { "EL2HLT",	N_("Level 2 halted") },
	[ EL2NSYNC ]	= { "EL2NSYNC",	N_("Level 2 not synchronized") },
	[ EL3HLT ]	= { "EL3HLT",	N_("Level 3 halted") },
	[ EL3RST ]	= { "EL3RST",	N_("Level 3 reset") },
	[ ELIBACC ]	= { "ELIBACC",	N_("Can not access a needed shared library") },
	[ ELIBBAD ]	= { "ELIBBAD",	N_("Accessing a corrupted shared library") },
	[ ELIBEXEC ]	= { "ELIBEXEC",	N_("Cannot exec a shared library directly") },
	[ ELIBMAX ]	= { "ELIBMAX",	N_("Attempting to link in too many shared libraries") },
	[ ELIBSCN ]	= { "ELIBSCN",	N_(".lib section in a.out corrupted") },
	[ ELNRNG ]	= { "ELNRNG",	N_("Link number out of range") },
	[ ELOOP ]	= { "ELOOP",	N_("Too many symbolic links encountered") },
	[ EMEDIUMTYPE ]	= { "EMEDIUMTYPE",	N_("Wrong medium type") },
	[ EMFILE ]	= { "EMFILE",	N_("Too many open files") },
	[ EMLINK ]	= { "EMLINK",	N_("Too many links") },
	[ EMSGSIZE ]	= { "EMSGSIZE",	N_("Message too long") },
	[ EMULTIHOP ]	= { "EMULTIHOP",	N_("Multihop attempted") },
	[ ENAMETOOLONG ]	= { "ENAMETOOLONG",	N_("File name too long") },
	[ ENAVAIL ]	= { "ENAVAIL",	N_("No XENIX semaphores available") },
	[ ENETDOWN ]	= { "ENETDOWN",	N_("Network is down") },
	[ ENETRESET ]	= { "ENETRESET",	N_("Network dropped connection because of reset") },
	[ ENETUNREACH ]	= { "ENETUNREACH",	N_("Network is unreachable") },
	[ ENFILE ]	= { "ENFILE",	N_("File table overflow") },
	[ ENOANO ]	= { "ENOANO",	N_("No anode") },
	[ ENOBUFS ]	= { "ENOBUFS",	N_("No buffer space available") },
	[ ENOCSI ]	= { "ENOCSI",	N_("No CSI structure available") },
	[ ENODATA ]	= { "ENODATA",	N_("No data available") },
	[ ENODEV ]	= { "ENODEV",	N_("No such device") },
	[ ENOENT ]	= { "ENOENT",	N_("No such file or directory") },
	[ ENOEXEC ]	= { "ENOEXEC",	N_("Exec format error") },
	[ ENOKEY ]	= { "ENOKEY",	N_("Required key not available") },
	[ ENOLCK ]	= { "ENOLCK",	N_("No record locks available") },
	[ ENOLINK ]	= { "ENOLINK",	N_("Link has been severed") },
	[ ENOMEDIUM ]	= { "ENOMEDIUM",	N_("No medium found") },
	[ ENOMEM ]	= { "ENOMEM",	N_("Out of memory") },
	[ ENOMSG ]	= { "ENOMSG",	N_("No message of desired type") },
	[ ENONET ]	= { "ENONET",	N_("Machine is not on the network") },
	[ ENOPKG ]	= { "ENOPKG",	N_("Package not installed") },
	[ ENOPROTOOPT ]	= { "ENOPROTOOPT",	N_("Protocol not available") },
	[ ENOSPC ]	= { "ENOSPC",	N_("No space left on device") },
	[ ENOSR ]	= { "ENOSR",	N_("Out of streams resources") },
	[ ENOSTR ]	= { "ENOSTR",	N_("Device not a stream") },
	[ ENOSYS ]	= { "ENOSYS",	N_("Function not implemented") },
	[ ENOTBLK ]	= { "ENOTBLK",	N_("Block device required") },
	[ ENOTCONN ]	= { "ENOTCONN",	N_("Transport endpoint is not connected") },
	[ ENOTDIR ]	= { "ENOTDIR",	N_("Not a directory") },
	[ ENOTEMPTY ]	= { "ENOTEMPTY",	N_("Directory not empty") },
	[ ENOTNAM ]	= { "ENOTNAM",	N_("Not a XENIX named type file") },
	[ ENOTRECOVERABLE ]	= { "ENOTRECOVERABLE",	N_("State not recoverable") },
	[ ENOTSOCK ]	= { "ENOTSOCK",	N_("Socket operation on non-socket") },
	[ ENOTSUP ]	= { "ENOTSUP",	N_("") },
	[ ENOTTY ]	= { "ENOTTY",	N_("Not a typewriter") },
	[ ENOTUNIQ ]	= { "ENOTUNIQ",	N_("Name not unique on network") },
	[ ENXIO ]	= { "ENXIO",	N_("No such device or address") },
	[ EOPNOTSUPP ]	= { "EOPNOTSUPP",	N_("Operation not supported on transport endpoint") },
	[ EOVERFLOW ]	= { "EOVERFLOW",	N_("Value too large for defined data type") },
	[ EOWNERDEAD ]	= { "EOWNERDEAD",	N_("Owner died") },
	[ EPERM ]	= { "EPERM",	N_("Operation not permitted") },
	[ EPFNOSUPPORT ]	= { "EPFNOSUPPORT",	N_("Protocol family not supported") },
	[ EPIPE ]	= { "EPIPE",	N_("Broken pipe") },
	[ EPROTO ]	= { "EPROTO",	N_("Protocol error") },
	[ EPROTONOSUPPORT ]	= { "EPROTONOSUPPORT",	N_("Protocol not supported") },
	[ EPROTOTYPE ]	= { "EPROTOTYPE",	N_("Protocol wrong type for socket") },
	[ ERANGE ]	= { "ERANGE",	N_("Math result not representable") },
	[ EREMCHG ]	= { "EREMCHG",	N_("Remote address changed") },
	[ EREMOTE ]	= { "EREMOTE",	N_("Object is remote") },
	[ EREMOTEIO ]	= { "EREMOTEIO",	N_("Remote I/O error") },
	[ ERESTART ]	= { "ERESTART",	N_("Interrupted system call should be restarted") },
	[ ERFKILL ]	= { "ERFKILL",	N_("Operation not possible due to RF-kill") },
	[ EROFS ]	= { "EROFS",	N_("Read-only file system") },
	[ ESHUTDOWN ]	= { "ESHUTDOWN",	N_("Cannot send after transport endpoint shutdown") },
	[ ESOCKTNOSUPPORT ]	= { "ESOCKTNOSUPPORT",	N_("Socket type not supported") },
	[ ESPIPE ]	= { "ESPIPE",	N_("Illegal seek") },
	[ ESRCH ]	= { "ESRCH",	N_("No such process") },
	[ ESRMNT ]	= { "ESRMNT",	N_("Srmount error") },
	[ ESTALE ]	= { "ESTALE",	N_("Stale NFS file handle") },
	[ ESTRPIPE ]	= { "ESTRPIPE",	N_("Streams pipe error") },
	[ ETIME ]	= { "ETIME",	N_("Timer expired") },
	[ ETIMEDOUT ]	= { "ETIMEDOUT",	N_("Connection timed out") },
	[ ETOOMANYREFS ]	= { "ETOOMANYREFS",	N_("Too many references: cannot splice") },
	[ ETXTBSY ]	= { "ETXTBSY",	N_("Text file busy") },
	[ EUCLEAN ]	= { "EUCLEAN",	N_("Structure needs cleaning") },
	[ EUNATCH ]	= { "EUNATCH",	N_("Protocol driver not attached") },
	[ EUSERS ]	= { "EUSERS",	N_("Too many users") },
	[ EWOULDBLOCK ]	= { "EWOULDBLOCK",	N_("Operation would block") },
	[ EXDEV ]	= { "EXDEV",	N_("Cross-device link") },
	[ EXFULL ]	= { "EXFULL",	N_("Exchange full") },
};

dict_t const errdict =	{
	names,
	sizeof(names) / sizeof(names[0])
};
