#!/bin/bash
ME=$(basename $0)
USAGE="usage: ${ME} [-o ofile]"
ofile=
while getopts o: c; do
	case "${c}" in
	o)	ofile="${OPTARG}";;
	*)	echo "${USAGE}" >&2; exit 1;;
	esac
done
shift $(expr ${OPTIND} - 1)
if [ "${ofile}" ]; then
	rm -f "${ofile}"
	exec >"${ofile}"
fi
export LANG=C
gcc -E -P tcp_states.h							|
awk '
BEGIN	{
	print "#include <unistd.h>"
	print "#include \"dict.h\""
	print "#include \"tcp_states.h\""
	print ""
	printf "static dict_entry_t const\tnames[] =\t{\n"
}
/TCP_/ {
	gsub( /,/, "", $1 )
	subscript = sprintf( "[%s]", $1 )
	name = sprintf( "\"%s\"", $1 )
	desc = sprintf( "\"%s\"", substr( $1, 5 ) )
	printf( "\t%-19s = { %20s, %s },\n", subscript, name, desc )
}
END	{
	printf "};\n"
	printf "\n"
	printf "dict_t\tconst\tnetdict =\t{\n"
	printf "\t\"Network\",\n"
	printf "\tnames,\n"
	printf "\tsizeof(names)/sizeof(names[0])\n", n
	printf "};\n"
}
'
exit $?
