#!/bin/bash
ME=$(basename $0)
USAGE="usage: ${ME} [-o ofile]"
ofile=
while getopts o: c; do
	case "${c}" in
	o)	ofile="${OPTARG}";;
	*)	echo "${USAGE}" >&2; exit 1;;
	esac
done
shift $(expr ${OPTIND} - 1)
if [ "${ofile}" ]; then
	rm -f "${ofile}"
	exec >"${ofile}"
fi
export LANG=C
cpp -E -CC -dD /usr/include/X11/X.h					|
sort -n -k3,3								|
awk '
BEGIN	{
	print "#ifdef\tHAVE_CONFIG_H"
	print "# include \"../config.h\""
	print "#endif"
	print "#include <unistd.h>"
	print "#include <X11/X.h>"
	print "#include \"dict.h\""
	print ""
	print "#if\tENABLE_NLS"
	print "# define\t_(x)\t\tgettext( x )"
	print "# define\tN_(x)\t\tx"
	print "#else"
	print "# define\t_(x)\t\tx"
	print "# define\tN_(x)\t\tx"
	print "#endif"
	print ""
	printf "static dict_entry_t const\tnames[] =\t{\n"
}
/^#define[[:space:]]/ {
	name = $2
	if( name ~ /^Success$/ || name ~ /^Bad/ )	{
		value = $3 + 0
		$1 = $2 = $3 = $4 = $NF = ""
		desc = $0
		sub( /^[[:space:]]*/, "", desc )
		sub( /[[:space:]]*$/, "", desc )
		printf( "  [ %s\t] = { \"%s\", \"%s\" },\n", name, name, desc )
	}
}
END	{
	printf "};\n"
	printf "dict_t const x11dict =\t{\n"
	printf "\t\"X11 Errors\",\n"
	printf "\tnames,\n"
	printf "\tsizeof(names)/sizeof(names[0])\n"
	printf "};\n"
}
'
