#!/bin/bash
ME=$(basename $0)
USAGE="usage: ${ME} [-o ofile] [rfc1945.txt]"
ofile=
while getopts o: c; do
	case "${c}" in
	o)	ofile="${OPTARG}";;
	*)	echo "${USAGE}" >&2; exit 1;;
	esac
done
shift $(expr ${OPTIND} - 1)
if [ "${ofile}" ]; then
	rm -f "${ofile}"
	exec >"${ofile}"
fi
export LANG=C
(
	if [[ $# -gt 0 ]]; then
		cat "$@"
	else
		curl -s http://www.ietf.org/rfc/rfc1945.txt
	fi
)									|
sed -nr -e 's/^.*"([[:digit:]]{3})"[[:space:]]*;[[:space:]]*(.*)$/\1 \2/p' |
sort -n									|
awk '
BEGIN	{
	print "#ifdef\tHAVE_CONFIG_H"
	print "# include \"../config.h\""
	print "#endif"
	print "#include <unistd.h>"
	print "#include <errno.h>"
	print "#include \"dict.h\""
	print ""
	print "#if\tENABLE_NLS"
	print "# define\t_(x)\t\tgettext( x )"
	print "# define\tN_(x)\t\tx"
	print "#else"
	print "# define\t_(x)\t\tx"
	print "# define\tN_(x)\t\tx"
	print "#endif"
	print ""
	printf "static dict_entry_t const \tnames[] =\t{\n"
}
$NF >= 2	{
	code = $1
	$1 = ""
	desc = $0
	sub( /^[[:space:]]*/, "", desc )
	sub( /[[:space:]]*$/, "", desc )
	printf( "\t[ %s ]\t= { \"%s\",\tN_(\"%s\") },\n", code, code, desc )
}
END	{
	printf "};\n"
	print ""
	printf "dict_t const webdict =\t{\n"
	printf "\t\"Network Sockets\",\n"
	printf "\tnames,\n"
	printf "\tsizeof(names) / sizeof(names[0])\n"
	printf "};\n"
}
'
