#!/bin/bash
ME=$(basename $0)
USAGE="usage: ${ME} [-o ofile]"
ofile=
while getopts o: c; do
	case "${c}" in
	o)	ofile="${OPTARG}";;
	*)	echo "${USAGE}" >&2; exit 1;;
	esac
done
shift $(expr ${OPTIND} - 1)
if [ "${ofile}" ]; then
	rm -f "${ofile}"
	exec >"${ofile}"
fi
export LANG=C
gcc -E -P tcp_states.h							|
awk '
BEGIN	{
	print "#include <unistd.h>"
	print "#include \"dict.h\""
	print "#include \"tcp_states.h\""
	print ""
}
/TCP_/ {
	gsub( /,/, "", $1 )
	names[ ++n ] = $1
	L = length( $1 )
	if( L > maxlen ) maxlen = L
}
END	{
	n = asort( names )
	sfmt = sprintf( "[%%-%d.%ds]", maxlen, maxlen )
	printf "dict_entry_t const\tnetdict[] =\t{\n", n
	for( i = 1; i <= n; ++i )	{
		s = names[i]
		subscript = sprintf( sfmt, s )
		printf( "\t%s = \"%s\",\n", subscript, s )
	}
	printf "};\n"
}
'
exit $?
