#!/bin/bash
ME=$(basename $0)
USAGE="usage: ${ME} [-o ofile]"
ofile=
while getopts o: c; do
	case "${c}" in
	o)	ofile="${OPTARG}";;
	*)	echo "${USAGE}" >&2; exit 1;;
	esac
done
shift $(expr ${OPTIND} - 1)
if [ "${ofile}" ]; then
	rm -f "${ofile}"
	exec >"${ofile}"
fi
export LANG=C
cpp -E -CC -dD /usr/include/X11/X.h					|
sort -n -k3,3								|
awk '
BEGIN	{
	print "#ifdef\tHAVE_CONFIG_H"
	print "# include \"../config.h\""
	print "#endif"
	print "#include <unistd.h>"
	print "#include <X11/X.h>"
	print "#include \"dict.h\""
	print ""
	print "#if\tENABLE_NLS"
	print "# define\t_(x)\t\tgettext( x )"
	print "# define\tN_(x)\t\tx"
	print "#else"
	print "# define\t_(x)\t\tx"
	print "# define\tN_(x)\t\tx"
	print "#endif"
	print ""
	maxname = 8
}
/^#define[[:space:]]/ {
	name = $2
	if( name ~ /^Success$/ || name ~ /^Bad/ )	{
		if( length(name) > maxname )	{
			maxname = length(name)
		}
		value = $3 + 0
		if( value > maxValue )	{
			maxValue = value
		}
		values[ value ] = name
		$1 = $2 = $3 = $4 = $NF = ""
		desc = $0
		sub( /^[[:space:]]*/, "", desc )
		sub( /[[:space:]]*$/, "", desc )
		descriptions[ name ] = desc
	}
}
END	{
	++maxValue
	printf "static dict_entry_t const\tnames[ %d ] =\t{\n", maxValue
	for( value = 0; value < maxValue; ++value )	{
		if( value in values )	{
			name = values[ value ]
			printf( "  [ %-*s ] =\t{\n", maxname, name )
			printf( "   \"%s\",\n", name )
			printf( "   N_(\"%s\")\n", descriptions[name] )
			printf( "  },\n" )
		}
	}
	printf "};\n"
	printf "dict_t const x11dict =\t{\n"
	printf "\tnames,\n"
	printf "\t%d\n", maxValue
	printf "};\n"
}
'
